### ISSUE TITLE
`--skip-content` removes "wp-content/languages" directory, breaking `--locale`

### ISSUE THREAD

**Issue by Luc45** [wp-cli/core-command#190] opened 2021-05-30 23:49 UTC
When using `wp core download` with the `--locale` and `--skip-content` flags, `--skip-content` will delete the `wp-content/languages` directory, where the localized files for WordPress are stored, leaving "English" as the only installed language.

https://github.com/wp-cli/core-command/blob/2435f99aedb5ec91093ea66dbb76297991fae0b1/src/Core_Command.php#L1416-L1418

How to reproduce:
1. `wp core download --skip-content --locale=pt_BR`
2. See that the `$wp_local_package` variable in `wp-includes/version.php` is `pt_BR`
3. Open the site in the browser. See that the Install Wizard is in **English**
4. See that the `wp-content` directory do not exist.
5. Delete the test site, download it again without `--skip-content`: `wp core download --locale=pt_BR` Run the assertions above, see that the Install Wizard is in `Brazilian Portuguese`, as expected.

**Comment by Luc45** [comment] 2021-05-30 23:54
This is what the default wp-content folder looks like, with locale:


```php
if ( false !== stripos( $info['name'], 'wp-content/plugins' ) || false !== stripos( $info['name'], 'wp-content/themes' ) ) {
	$zip->deleteIndex( $i );
}
```

**Comment by maximejobin** [comment] 2023-03-09 12:05
Based on this commit https://github.com/wp-cli/core-command/commit/ded2cab609c9764fff5f2741d9f3de0d93ec72da, I would say this issue is solved.

I could not reproduce the issue anymore, can see the `languages` folder and the `$wp_local_package` has the right value.

@schlessera or @danielbachhuber : can we close this?

**Comment by danielbachhuber** [comment] 2023-03-09 14:14
@maximejobin Yes, I think so too. Thanks for flagging!

**Closed by danielbachhuber** 2023-03-09 14:14 UTC
