### ISSUE TITLE
As of Wordpress 5.5 'wp core update' results in PHP Warning (WP-CLI 2.4.0)

### ISSUE THREAD

**Issue by fawp** [wp-cli/core-command#170] opened 2020-10-01 08:43 UTC
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Note**: this was reported by kkmuffme [here](https://github.com/wp-cli/core-command/issues/169) as affecting WP-CLI 2.5.0-alpha-75cb7e3 dev version, although it looks like it is also affecting 2.4.0

**Describe the current, buggy behavior**
On a fresh WordPress 5.5 install, updating core via `wp core update` results in the following warning

```
Updating to version 5.5.1 (en_US)...
PHP Warning:  Declaration of WP_CLI\Core\CoreUpgrader::download_package($package, $check_signatures = true) should be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = Array) in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/WP_CLI/Core/CoreUpgrader.php on line 163
Warning: Declaration of WP_CLI\Core\CoreUpgrader::download_package($package, $check_signatures = true) should be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = Array) in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/WP_CLI/Core/CoreUpgrader.php on line 163
Downloading update from https://downloads.wordpress.org/release/wordpress-5.5.1-partial-0.zip...
Unpacking the update...
Success: WordPress updated successfully.
```
It looks like WordPress is still updated, though.

Presumably the incompatibility warning is about the function _download_package_ (```wp-admin/includes/class-wp-upgrader.php```) which was updated in WordPress 5.5 from 5.4.2, but not in WP-CLI 2.4.0.

**Describe how other contributors can replicate this bug**

Install a fresh copy of WP 5.5 as follows
- ```wp core download --version=5.5```
- ```wp config create --dbname=<dbname> --dbuser=<dbuser> --dbpass=<dbpass>```
- ```wp db create```
- ```wp core install --url=<url> --title=<site-title> --admin_user=<username> --admin_email=<email>```

Update the fresh WP install as follows
- ```wp core update```

These step will result in the warning above.

**Describe what you would expect as the correct outcome**

I would not expect the warning.

**Let us know what environment you are running this on**

```
OS:	Linux 4.19.0-10-686 #1 SMP Debian 4.19.132-1 (2020-07-24) i686
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.3
PHP version:	7.3.19-1~deb10u1
php.ini used:	/etc/php/7.3/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/php.test
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0
```

**Provide a possible solution**

Update function _download_package_ in next in WP-CLI version so as to align to updated _download_package_  in ```wp-admin/includes/class-wp-upgrader.php```

**Comment by schlessera** [comment] 2020-10-01 10:58
This is a duplicate of issue https://github.com/wp-cli/core-command/issues/167, which was already fixed in the latest code which will be included with release v2.5.0.

You can already test the fix with the WP-CLI nightly version, which you can use via `wp cli update --nightly`.

**Comment by schlessera** [comment] 2020-10-01 10:59
Nevertheless, thanks for your effort in writing this detailed bug report, @fawp !

**Closed by schlessera** 2020-10-01 10:58 UTC

**Comment by andykillen** [comment] 2021-02-03 08:11
I just had this problem going from 5.5.1 to 5.6 core release version. To get over it I did

```
wp plugin update --all
wp theme update --all
wp core download --force
wp core update-db
```

OK, updating the themes and plugins was not strictly necessary, but good practice. 

The **download --force** and **update-db** perform pretty much the same process as **core update**.
