### ISSUE TITLE
Automatic translation update of core / bundled core plugin looks messy

### ISSUE THREAD

**Issue by GaryJones** [wp-cli/core-command#31] opened 2017-08-31 12:41 UTC
Running `wp core update` when:
- core is outdated _AND_
- site is running on a non-US English site _AND_
- core has new strings _OR_
- core is bundled with a version of Akismet that has new strings.

gives the following:

![screenshot 2017-08-31 13 36 53](https://user-images.githubusercontent.com/88371/29923504-ab434d8c-8e51-11e7-9ae0-89a39ec6b03b.png)

All seems to have worked, but the extra feedback includes messy HTML and JS.

**Comment by danielbachhuber** [comment] 2017-08-31 12:48
Duplicate of https://github.com/wp-cli/wp-cli/issues/1501

Feel free to re-open https://core.trac.wordpress.org/ticket/30497 with reproduction steps and/or a suggested fix.

**Closed by danielbachhuber** 2017-08-31 12:48 UTC
